apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: prometheus-stack

resources:
  - configmap.yaml
  - helmrepository.yaml
  - helmrelease.yaml

commonLabels:
  app.kubernetes.io/name: kube-prometheus-stack
  app.kubernetes.io/part-of: demo-app-python-assignment
  app.kubernetes.io/component: infrastructure
  app.kubernetes.io/version: v55.5.0
  app.kubernetes.io/managed-by: flux
