apiVersion: v1
kind: Namespace
metadata:
  name: dev
  labels:
    app.kubernetes.io/name: dev
    app.kubernetes.io/part-of: kaiko-assignment
    app.kubernetes.io/environment: development
    app.kubernetes.io/tier: application
