apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: flux-cd-root
  namespace: flux-system

resources:
  - bootstrap/flux-system
  - applications

commonLabels:
  app.kubernetes.io/part-of: kaiko-assignment
  app.kubernetes.io/component: flux-cd
