apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: applications

resources:
  - mock-cluster-aka-namespaces/dev
  - mock-cluster-aka-namespaces/staging
  - mock-cluster-aka-namespaces/production

commonLabels:
  app.kubernetes.io/part-of: kaiko-assignment
  app.kubernetes.io/component: applications
