# This file now only contains the Kustomization for applications
# The GitRepository is managed centrally in flux-cd/gitrepositories.yaml

apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: applications
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./flux-cd/applications
  prune: true
  sourceRef:
    kind: GitRepository
    name: applications
  targetNamespace: flux-system
