apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: demo-app-python-production

resources:
  - ../../../_base-app-config

namespace: production

commonLabels:
  app.kubernetes.io/environment: production
  app.kubernetes.io/tier: production
  app.kubernetes.io/implementation: python

patches:
  - target:
      kind: Deployment
      name: demo-app
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: demo-app-python:latest
      - op: replace
        path: /spec/replicas
        value: 3
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: 200m
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: 256Mi
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: 400m
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: 512Mi
