apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: app-pdb
  namespace: app
  labels:
    app.kubernetes.io/name: app
    app.kubernetes.io/part-of: kaiko-assignment
spec:
  minAvailable: 50%
  selector:
    matchLabels:
      app.kubernetes.io/name: app
      app.kubernetes.io/part-of: kaiko-assignment