apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: app
  labels:
    app.kubernetes.io/name: app
    app.kubernetes.io/part-of: kaiko-assignment
type: Opaque
stringData:
  GREETING: "hello"