apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      serviceAccountName: app-sa
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: DoesNotExist
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        runAsGroup: 10001
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: app
          image: localhost:5000/app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8000
          env:
            - name: GREETING
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: GREETING
            - name: FAIL_RATE
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: FAIL_RATE
            - name: READINESS_DELAY_SEC
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: READINESS_DELAY_SEC
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8000
            periodSeconds: 2
            timeoutSeconds: 1
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8000
            periodSeconds: 10
            timeoutSeconds: 1
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
          volumeMounts:
            - name: tmp
              mountPath: /tmp
              readOnly: false
      volumes:
        - name: tmp
          emptyDir: {}

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-sa
---
apiVersion: v1
kind: Service
metadata:
  name: app
spec:
  selector:
    app: app
  ports:
    - port: 80
      targetPort: http

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  FAIL_RATE: "0.02"
  READINESS_DELAY_SEC: "10"

---

apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
stringData:
  GREETING: "hello"

---

apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: app-pdb
spec:
  minAvailable: 50%
  selector:
    matchLabels:
      app: app