apiVersion: v1
kind: ConfigMap
metadata:
  name: alloy-config
  namespace: monitoring
data:
  config.alloy: |
    // Basic Alloy configuration for OpenTelemetry
    logging {
      level = "info"
      format = "logfmt"
    }

    // OTLP receiver for metrics and traces - this is where your apps will send data
    otelcol.receiver.otlp "default" {
      grpc {
        endpoint = "0.0.0.0:4317"
      }
      http {
        endpoint = "0.0.0.0:4318"
      }
      
      output {
        metrics = [otelcol.processor.resourcedetection.basic_detection.input]
        traces  = [otelcol.processor.resourcedetection.basic_detection.input]
      }
    }

    // Note: Loki doesn't support OTLP for logs
    // Apps should send logs via standard logging (stdout/stderr) which will be collected by loki.source.kubernetes

    // Step 1: Detect basic resource attributes
    otelcol.processor.resourcedetection "basic_detection" {
      detectors = ["env", "system"]
      
      output {
        metrics = [otelcol.processor.transform.namespace_to_env.input]
        logs    = [otelcol.processor.transform.namespace_to_env.input]
        traces  = [otelcol.processor.transform.namespace_to_env.input]
      }
    }

    // Step 2: Transform namespace to environment and add custom attributes
    otelcol.processor.transform "namespace_to_env" {
      error_mode = "ignore"
      
      metric_statements {
        context = "resource"
        statements = [
          "set(attributes[\"environment\"], attributes[\"k8s.namespace.name\"]) where attributes[\"k8s.namespace.name\"] != nil",
          "set(attributes[\"cluster_name\"], \"kind-cluster\") where true",
          "set(attributes[\"collector\"], \"alloy\") where true",
        ]
      }
      
      log_statements {
        context = "resource"
        statements = [
          "set(attributes[\"environment\"], attributes[\"k8s.namespace.name\"]) where attributes[\"k8s.namespace.name\"] != nil",
          "set(attributes[\"cluster_name\"], \"kind-cluster\") where true", 
          "set(attributes[\"collector\"], \"alloy\") where true",
        ]
      }
      
      trace_statements {
        context = "resource"
        statements = [
          "set(attributes[\"environment\"], attributes[\"k8s.namespace.name\"]) where attributes[\"k8s.namespace.name\"] != nil",
          "set(attributes[\"cluster_name\"], \"kind-cluster\") where true",
          "set(attributes[\"collector\"], \"alloy\") where true", 
        ]
      }
      
      output {
        metrics = [otelcol.exporter.prometheus.prometheus.input]
        traces  = [otelcol.exporter.otlp.tempo.input]
      }
    }

    // Export metrics to Prometheus format
    otelcol.exporter.prometheus "prometheus" {
      forward_to = [prometheus.remote_write.prometheus.receiver]
    }

    // Export metrics to Mimir (Prometheus-compatible) via remote write
    prometheus.remote_write "prometheus" {
      endpoint {
        url = "http://lgtm-stack-mimir-nginx:80/api/v1/push"
      }
    }


    // Export logs to Loki via HTTP API
    loki.write "loki" {
      endpoint {
        url = "http://lgtm-stack-loki-gateway:80/loki/api/v1/push"
      }
    }

    // Export traces to Tempo via OTLP gRPC
    otelcol.exporter.otlp "tempo" {
      client {
        endpoint = "http://lgtm-stack-tempo-distributor:9095"
        tls {
          insecure = true
        }
      }
    }

    // Export logs to Loki via HTTP API (not OTLP - Loki doesn't support OTLP for logs)
    // We'll use a different approach for app logs vs pod logs

    // Log collection from Kubernetes pods (simplified)
    discovery.kubernetes "pods" {
      role = "pod"
    }

    discovery.relabel "pods" {
      targets = discovery.kubernetes.pods.targets
      rule {
        source_labels = ["__meta_kubernetes_namespace"]
        target_label  = "namespace"
      }
      rule {
        source_labels = ["__meta_kubernetes_pod_name"]
        target_label  = "pod"
      }
      rule {
        source_labels = ["__meta_kubernetes_pod_container_name"]
        target_label  = "container"
      }
    }

    loki.source.kubernetes "pods" {
      targets    = discovery.relabel.pods.output
      forward_to = [loki.write.loki.receiver]
    }

    // OTLP-only approach - no Prometheus scraping
    // Your apps will send metrics directly via OTLP to ports 4317/4318
