apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: grafana
  namespace: monitoring
  labels:
    app.kubernetes.io/component: infrastructure
    app.kubernetes.io/environment: shared
    app.kubernetes.io/managed-by: flux
    app.kubernetes.io/name: infrastructure
    app.kubernetes.io/part-of: demo-app-python-assignment
    app.kubernetes.io/tier: monitoring
spec:
  interval: 5m
  url: https://grafana.github.io/helm-charts
