apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: app-staging
  namespace: staging

resources:
  - ../../../base-app-config

namespace: staging

commonLabels:
  app.kubernetes.io/environment: staging
