apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: production-environment
  namespace: production

resources:
  - namespace.yaml
  - ../../base-app-config

commonLabels:
  app.kubernetes.io/part-of: kaiko-assignment
  app.kubernetes.io/environment: production

# Namespace transformation patches
patches:
  - target:
      kind: Deployment
      name: app
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: production
  - target:
      kind: Service
      name: app
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: production
  - target:
      kind: ConfigMap
      name: app-config
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: production
  - target:
      kind: Secret
      name: app-secret
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: production
  - target:
      kind: ServiceAccount
      name: app-sa
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: production
  - target:
      kind: NetworkPolicy
      name: app-network-policy
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: production
  # Resource allocation patches
  - target:
      kind: Deployment
      name: app
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: 250m
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: 256Mi
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: 500m
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: 512Mi
