apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: production-environment

namespace: production

resources:
  - namespace.yaml
  - ../../_base-app-config

labels:
  - pairs:
      app.kubernetes.io/part-of: kaiko-assignment
      app.kubernetes.io/environment: production
      app.kubernetes.io/tier: production

# Resource allocation patches
patches:
  - target:
      kind: Deployment
      name: app
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: 200m
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: 256Mi
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: 500m
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: 512Mi
