apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: app-dev
  namespace: dev

resources:
  - ../../../base-app-config

namespace: dev

commonLabels:
  app.kubernetes.io/environment: development
