apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: infrastructure
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: flux-system  # Reuse the same SSH key
  timeout: 60s
  url: ssh://git@github.com/phaidon-passias/kaiko-assignment
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./flux-cd/infrastructure
  prune: true
  sourceRef:
    kind: GitRepository
    name: infrastructure
  targetNamespace: flux-system
