# This file now only contains the Kustomization for infrastructure
# The GitRepository is managed centrally in flux-cd/gitrepositories.yaml

apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./flux-cd/infrastructure
  prune: true
  sourceRef:
    kind: GitRepository
    name: infrastructure
  targetNamespace: flux-system
  resources:
    - monitoring-stack/
