apiVersion: v1
kind: ConfigMap
metadata:
  name: k8s-monitoring-values
  namespace: monitoring
data:
  values.yaml: |
    # Cluster configuration
    cluster:
      name: kind-cluster

    # Global settings
    global:
      scrapeInterval: 60s
      scrapeTimeout: 10s

    # Destinations - where to send telemetry data
    destinations: []
    
    # Destinations map - actual destination definitions
    destinationsMap:
      # Prometheus destination for metrics
      prometheus:
        type: prometheus
        url: http://lgtm-stack-prometheus:9090/api/v1/write
        # Enable remote write receiver
        remoteWrite:
          enabled: true

      # Loki destination for logs
      loki:
        type: loki
        url: http://lgtm-stack-loki:3100/loki/api/v1/push

      # Tempo destination for traces
      tempo:
        type: otlp
        url: http://lgtm-stack-tempo:3200

    # Features - what to monitor
    clusterMetrics:
      enabled: true
      destinations: ["prometheus"]

    # Grafana configuration
    grafana:
      enabled: true
      adminPassword: admin
      persistence:
        enabled: true
        size: 5Gi
      service:
        type: ClusterIP
      resources:
        requests:
          memory: 128Mi
          cpu: 100m
        limits:
          memory: 512Mi
          cpu: 200m

    # Prometheus configuration
    prometheus:
      enabled: true
      server:
        retention: 168h
        persistentVolume: 
          enabled: true
          size: 10Gi
        resources:
          requests:
            memory: 256Mi
            cpu: 100m
          limits:
            memory: 1Gi
            cpu: 500m
        # Enable remote write receiver for Alloy
        extraArgs:
          - --web.enable-remote-write-receiver

    # Loki configuration
    loki:
      enabled: true
      persistence:
        enabled: true
        size: 10Gi
      resources:
        requests:
          memory: 128Mi
          cpu: 100m
        limits:
          memory: 512Mi
          cpu: 200m

    # Alertmanager configuration
    alertmanager:
      enabled: true
      persistence:
        enabled: true
        size: 5Gi
      resources:
        requests:
          memory: 128Mi
          cpu: 100m
        limits:
          memory: 256Mi
          cpu: 200m

    # Tempo configuration (for traces)
    tempo:
      enabled: true
      persistence:
        enabled: true
        size: 10Gi
      resources:
        requests:
          memory: 128Mi
          cpu: 100m
        limits:
          memory: 512Mi
          cpu: 200m

    # Node exporter
    nodeExporter:
      enabled: true

    # Kube state metrics
    kubeStateMetrics:
      enabled: true

    # Collectors (Alloy instances)
    alloy-metrics:
      enabled: true

    alloy-singleton:
      enabled: true