apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: k8s-monitoring
  namespace: monitoring
spec:
  interval: 5m0s
  chart:
    spec:
      chart: k8s-monitoring
      version: "3.5.2"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: monitoring
  valuesFrom:
    - kind: ConfigMap
      name: k8s-monitoring-values
      valuesKey: values.yaml
